### ISSUE TITLE
Can we contribute to this?

### ISSUE THREAD

**Issue by DavidSchirduan** [brunobord/micro-rpg-catalog#30]
I have 2 micro-rpgs that I'd love to add to your catalog, as well as links to the 200wordRPG website.

But I don't want to infringe on your curation and mess with your formula.

Let me know if you'd be open to that!

        - David

**Comment by brunobord** [comment]
Hi David.
I already thought about linking to the 200 word RPG website ; that's a good idea to hyperlink other references.

If you want, you can also give me a link to the games you'd like to add, I'll read them with much interest.

**Comment by DavidSchirduan** [comment]
Awesome! Thanks for linking to 200WordRPG!

As for my games, here they are: Kintsugi and Welcome Minions. I hope you enjoy they, regardless of whether they make it into your collection:
https://technicalgrimoire.com/david/my-creations/welcome-minions

https://technicalgrimoire.com/david/kintsugi

**Comment by brunobord** [comment]
I finally took the time to read your nice RPGs. They're very good, I especially enjoyed *Kintsugi*, it's interesting to see how a 200-word RPG can become a expanded game, without becoming too large or too crunchy.

Unfortunately, I think they're a bit too long for being considered as "Micro".
Thank you very much for suggesting them, though, I'll keep an eye on the Kintsugi PDF and would eventually try to give it a go.

**Comment by DavidSchirduan** [comment]
Of course! Thanks for the kind words, and thanks for keeping up with awesome repository. I look forward to checking it every so often for new games.

     - David
